vich_uploader:
    db_driver: orm

    mappings:
        profile:
            uri_prefix: /images/profile
            upload_destination: '%kernel.project_dir%/public/images/profile'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_remove: false
            delete_on_update: false